### ISSUE TITLE
Problems with class callback!

### ISSUE THREAD

**Issue by Vando-Viriato** [ehong-tl/mqttsn-python3-micropython#2]
Hello!
I have a project where I need to use MQTT-SN clients, I took this repository as a reference, but I'm having a problem with the "callback" class!
When publish publish something it is for subscribe to receive, but does not receive or print the notice that the message has arrived.
Detail: I can see that the publisher published the topic and the gateway forwarded it to subscribe.
Can anyone help with this problem?

**Comment by ehong-tl** [comment]
Hi @Vando-Viriato ,

Did you mean your subscriber cannot print the message received?

**Comment by Vando-Viriato** [comment]
That's right, my subscribe does not print the message received. I am using the eclipse paho gateway.

**Comment by ehong-tl** [comment]
Hi @Vando-Viriato ,

I've tried it with eclipse paho mqtttsn gateway, everything's working fine. You should be able to get the message if you follow the subscriber example.

Or may be you can share your python code here and I'll try to resolve the problem.

**Comment by Vando-Viriato** [comment]
Hello @ehong-tl !
Thanks for helping me, I'll attach the code and some screenshots for you to see.

**Comment by Vando-Viriato** [comment]
Hello @ehong-tl 
[Vando_MQTT-SN.zip](https://github.com/ehong-tl/mqttsn-python3-micropython/files/4777359/Vando_MQTT-SN.zip)

I had a problem with my IDE to run pyton code, I am attaching the code as agreed.
Below is a zip file with the code, print of the gateway and exit of the clients. You can see on the output screen that the subscribe does not receive the message published by the publish.
Please help me find out what I'm doing wrong. Thank you!

**Comment by ehong-tl** [comment]
Hi @Vando-Viriato ,

The problem comes from your publisher.

You need to register the topic using aclient.register("...") method in your publisher, which you have commented out.

Please uncomment the register_topic() function and try again, it should be working now.

**Comment by Vando-Viriato** [comment]
Yes I ended up commenting unintentionally, I commented everything that has to do with topic 2 and topic 3 to test only topic 1, because I was giving an error with topics 2 and 3.
According to the code it was for the subscriber to receive "Hello world" published by the publisher. Can you understand what is happening?
I attached some screen prints.

![Test](https://user-images.githubusercontent.com/66709014/84716953-ea34f000-af4a-11ea-9232-049d8c1bcff6.png)
![Test _](https://user-images.githubusercontent.com/66709014/84716981-fc169300-af4a-11ea-96af-6212bb3d2079.png)
![Print](https://user-images.githubusercontent.com/66709014/84717040-21a39c80-af4b-11ea-890f-918ad5e1a904.png)

**Comment by Vando-Viriato** [comment]
Hi @ehong-tl 
Yes I ended up commenting unintentionally, I commented everything that has to do with topic 2 and topic 3 to test only topic 1, because I was giving an error with topics 2 and 3.
According to the code it was for the subscriber to receive "Hello world" published by the publisher. Can you understand what is happening?
I attached some screen prints.

[Prints.zip](https://github.com/ehong-tl/mqttsn-python3-micropython/files/4783570/Prints.zip)

**Comment by ehong-tl** [comment]
Hi @Vando-Viriato ,

I see you are running both the subscriber and publisher in the same IDE instance, this may be the reason the subscriber stopped running when publisher is executed, hence you will not see the message arrived to subscriber to be printed. Can you try running them in separate IDE instances?

**Comment by Vando-Viriato** [comment]
So I would have to be using two IDE's is that?
I'll try to do that, anything I tell you here.

**Comment by ehong-tl** [comment]
You can run them in the same IDE but different instances.

**Comment by Vando-Viriato** [comment]
Ok thanks @ehong-tl , I'm going to take the test and tell you if it worked.

**Comment by Vando-Viriato** [comment]
good evening @ehong-tl 
I ran the publisher and subscriber in different instances, but the subscriber still doesn't receive any messages. You can see in the prints I'm sending that I ran the publisher three times, but nothing.
I suspect the Callback class, I just can't see where the error is.
[Vando.zip](https://github.com/ehong-tl/mqttsn-python3-micropython/files/4789598/Vando.zip)

**Comment by ehong-tl** [comment]
Hi Vando-Viriato,

Can you share your latest code again?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Vando-Viriato** [comment]
Yes @ehong-tl 
I'm sending, follow the updated code in zip file. Thank you!

[Vando_MQTT-SN_Code.zip](https://github.com/ehong-tl/mqttsn-python3-micropython/files/4792358/Vando_MQTT-SN_Code.zip)

**Comment by ehong-tl** [comment]
Hi Vando-Viriato,

I have no problem running your code.

May be it’s  because something wrong to your gateway config?

Or may be you can try to run on another PC?


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Vando-Viriato** [comment]
Hi @ehong-tl 
I'll send you the configuration file of my gateway for you to see if something is not matching with the clients. I think I set up the gateway correctly, but I may have made a mistake

**Comment by ehong-tl** [comment]
Hi Vando-Viriato,

Please try to use the default one first.

https://github.com/eclipse/paho.mqtt-sn.embedded-c/blob/master/MQTTSNGateway/gateway.conf



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Vando-Viriato** [comment]
OK. I'm going to do it.

Enviada do Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by Vando-Viriato** [comment]
Hello @ehong-tl 
First of all thank you very much for taking the time to help me, I come to tell you that with the default configuration of the gateway my code worked!
But I was left with some doubts I don't know if I could explain myself, I will say each doubt with the print I made!

**Comment by Vando-Viriato** [comment]
In the following print I'm only using topic 1 for testing, the rest was commented. I ran the publisher a second time with a different message, but the subscriber did not receive it! Did this happen on your test?
![FUNC](https://user-images.githubusercontent.com/66709014/84939109-394a6480-b0b4-11ea-9f82-47a0257c878c.png)

**Comment by Vando-Viriato** [comment]
In this print I'm already using the three topics, do you notice that only topic 2 received a message and had nothing to do with the content published in the same topic?

![FUNC2](https://user-images.githubusercontent.com/66709014/84939796-43209780-b0b5-11ea-9c11-7b42a5be49e9.png)

**Comment by Vando-Viriato** [comment]
In this print, I disconnect the two clients and connect again, only then that the subscriber receives all the published messages, however, he receives two messages from topic 2! Understand it? Thank you @ehong-tl 

![FUNC*](https://user-images.githubusercontent.com/66709014/84940756-abbc4400-b0b6-11ea-8222-fd8f1a684ecb.png)

**Comment by ehong-tl** [comment]
Hi Vando-Viriato,

This is because your gateway is connected to a public broker, and there is someone out there is using the same topic name, please use a different topic name and try again.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by Vando-Viriato** [comment]
Hi @ehong-tl 
Oh I get it, so I'll change the topic name and test.

**Comment by Vando-Viriato** [comment]
Good evening @ehong-tl 
I did the test with several different topic names but it didn't work, I wanted to use a local broker, because I installed the mosquitto broker on my PC.
What should I change to make the gateway work with my broker? Thank you!

**Comment by ehong-tl** [comment]
Hi @Vando-Viriato ,

To change broker, please change line 17 and 18 of your gateway config file to your respective broker ip and port number.

BrokerName=mqtt.eclipse.org
BrokerPortNo=1883

**Comment by Vando-Viriato** [comment]
OK @ehong-tl 
I will modify and test.

**Comment by Vando-Viriato** [comment]
Hello @ehong-tl 
Thank you very much for all the help, I want to tell you that my code is running normally, publishing and receiving topics.
Now, I am adapting to my project, I am very grateful for you.

**Comment by ehong-tl** [comment]
You're welcome, good to hear that.
